# Generated by Django 3.1.4 on 2020-12-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
